package com.syntj.skyrim

enum class Effects (val description: String){
    CureDisease("Cure Disease"),
    DamageHealth("Damage Health"),
    DamageMagicka("Damage Magicka"),
    DamageMagickaRegen("Damage Magicka Regen"),
    DamageStamina("Damage Stamina"),
    DamageStaminaRegen("Damage Stamina Regen"),
    Fear("Fear"),
    FortifyAlteration("Fortify Alteration"),
    FortifyBarter("Fortify Barter"),
    FortifyBlock("Fortify Block"),
    FortifyCarryWeight("Fortify Carry Weight"),
    FortifyConjuration("Fortify Conjuration"),
    FortifyDestruction("Fortify Destruction"),
    FortifyEnchanting("Fortify Enchanting"),
    FortifyHealth("Fortify Health"),
    FortifyHeavyArmor("Fortify Heavy Armor"),
    FortifyIllusion("Fortify Illusion"),
    FortifyLightArmor("Fortify Light Armor"),
    FortifyLockpicking("Fortify Lockpicking"),
    FortifyMagicka("Fortify Magicka"),
    FortifyMarksman("Fortify Marksman"),
    FortifyOneHanded("Fortify One-handed"),
    FortifyPickpocket("Fortify Pickpocket"),
    FortifyRestoration("Fortify Restoration"),
    FortifySmithing("Fortify Smithing"),
    FortifySneak("Fortify Sneak"),
    FortifyStamina("Fortify Stamina"),
    FortifyTwoHanded("Fortify Two-handed"),
    Frenzy("Frenzy"),
    Invisibility("Invisibility"),
    LingeringDamageHealth("Lingering Damage Health"),
    LingeringDamageMagicka("Lingering Damage Magicka"),
    LingeringDamageStamina("Lingering Damage Stamina"),
    Paralysis("Paralysis"),
    RavageHealth("Ravage Health"),
    RavageMagicka("Ravage Magicka"),
    RavageStamina("Ravage Stamina"),
    RegenerateHealth("Regenerate Health"),
    RegenerateMagicka("Regenerate Magicka"),
    RegenerateStamina("Regenerate Stamina"),
    ResistFire("Resist Fire"),
    ResistFrost("Resist Frost"),
    ResistMagic("Resist Magic"),
    ResistPoison("Resist Poison"),
    ResistShock("Resist Shock"),
    RestoreHealth("Restore Health"),
    RestoreMagicka("Restore Magicka"),
    RestoreStamina("Restore Stamina"),
    Slow("Slow"),
    Waterbreathing("Waterbreathing"),
    WeaknessToFire("Weakness to Fire"),
    WeaknessToFrost("Weakness to Frost"),
    WeaknessToMagic("Weakness to Magic"),
    WeaknessToPoison("Weakness to Poison"),
    WeaknessToShock("Weakness to Shock"),
}
